name = "fiszki10devx"
main = "./dist/server/entry.mjs"
compatibility_date = "2024-03-23"

# Konfiguracja Workers
workers_dev = true
compatibility_flags = ["nodejs_compat"]

# Source maps dla debugowania
upload_source_maps = true

# Konfiguracja środowiska
[vars]
SITE_URL = "https://fiszki10devx.pages.dev"
SITE_NAME = "Fiszki10DevX"

# Konfiguracja budowania
[build]
command = "npm run build"
watch_dir = "src"

# Konfiguracja routingu
routes = [
  { pattern = "*/*", zone_name = "fiszki10devx.pages.dev" }
]

# Konfiguracja statycznych assetów
[site]
bucket = "./dist/client"
entry-point = "./dist/server/entry.mjs"

# Konfiguracja dla różnych środowisk
[env.production]
workers_dev = false
route = "fiszki10devx.pages.dev/*"

[env.staging]
name = "fiszki10devx-staging"
workers_dev = true

# Konfiguracja zmiennych dla różnych środowisk
[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"
